name: Evaluate model on Pull request

on:
  pull_request:
    types: ["opened", "reopened"]

env:
  MODEL_PATH: predictions/CAML_mimic3_full/model.pth

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Setup conda Environment
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     activate-environment: caml
      #     environment-file: environment.yml
      #     python-version: 3.6
      #     auto-activate-base: false
      # - name: Evaluate model
      #   id: eval
      #   shell: bash -l {0}
      #   run: |
      #     dvc remote modify --local mimic connection_string ${{ secrets.AZURE_CONNECTION_STRING }}
      #     dvc pull
      #     PYTHONPATH=. python learn/training.py train_full.csv vocab.csv full conv_attn 200 --filter-size 10 --num-filter-maps 50 --dropout 0.2 --patience 10 --lr 0.0001 --test-model predictions/reproCAML_mimic3_full/model.pth
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment