name: Create and Publish BentoML Service

on:
  push:
    tags: ["o*.*.*"]

env:
  FRONTEND_REPO: schlevik/caml-static
  ASSET_NAME: caml-model

jobs:
  onnx-build:
    name: Create ONNX artefact
    runs-on: ubuntu-latest
    steps:
      - name: Gets latest created release info
        id: release
        uses: jossef/action-latest-release-info@v1.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: caml2
          environment-file: environment2.yml
          python-version: 3.8
          auto-activate-base: true
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Log into registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: trace onnx model and publish artefact
        shell: bash -l {0}
        run: |
          PYTHONPATH=. python learn/trace_onnx.py conv_attn dicts.json label_desc.json --filter-size 10 --num-filter-maps 50 --test-model ./predictions/reproCAML_mimic3_full/model.pth --out-file caml-${{ steps.tag.outputs.tag }}.onnx
      - name: Upload release binary
        id: upload_model
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: caml-${{ steps.tag.outputs.tag }}.onnx
          asset_name: ${{env.ASSET_NAME}}
          asset_content_type: application/octet-stream
      - name: Upload dicts.json
        uses: actions/upload-release-asset@v1.0.2
        id: upload_dict
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: dicts.json
          asset_name: dicts
          asset_content_type: application/octet-stream
      - name: Notify Frontend of new release
        shell: bash -l {0}
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${{env.FRONTEND_REPO}}/dispatches --data '{"event_type":"new-artefact-created","client_payload":{"url":"https://github.com/${{github.repository}}/releases/download/${{ steps.tag.outputs.tag }}/${{env.ASSET_NAME}}","version":"${{ steps.tag.outputs.tag }}"}'